export const COUNTRY_CODES = [
  { label: "Pakistan (+92)", value: "Pakistan (+92)" },
  { label: "India (+91)", value: "India (+91)" },
  { label: "USA (+1)", value: "USA (+1)" },
  { label: "UK (+44)", value: "UK (+44)" },
  { label: "United Arab Emirates (+971)", value: "United Arab Emirates (+971)" },
  { label: "Saudi Arabia (+966)", value: "Saudi Arabia (+966)" },
  { label: "Qatar (+974)", value: "Qatar (+974)" },
  { label: "Kuwait (+965)", value: "Kuwait (+965)" },
  { label: "Oman (+968)", value: "Oman (+968)" },
  { label: "Bahrain (+973)", value: "Bahrain (+973)" },
  { label: "Switzerland (+41)", value: "Switzerland (+41)" },
  { label: "Germany (+49)", value: "Germany (+49)" },
  { label: "France (+33)", value: "France (+33)" },
  { label: "Italy (+39)", value: "Italy (+39)" },
  { label: "Spain (+34)", value: "Spain (+34)" },
  { label: "Netherlands (+31)", value: "Netherlands (+31)" },
  { label: "Belgium (+32)", value: "Belgium (+32)" },
  { label: "Austria (+43)", value: "Austria (+43)" },
  { label: "Sweden (+46)", value: "Sweden (+46)" },
  { label: "Norway (+47)", value: "Norway (+47)" },
  { label: "Denmark (+45)", value: "Denmark (+45)" },
  { label: "Ireland (+353)", value: "Ireland (+353)" },
  { label: "Canada (+1)", value: "Canada (+1)" },
  { label: "Australia (+61)", value: "Australia (+61)" },
  { label: "New Zealand (+64)", value: "New Zealand (+64)" },
  { label: "Bangladesh (+880)", value: "Bangladesh (+880)" },
  { label: "Sri Lanka (+94)", value: "Sri Lanka (+94)" },
  { label: "Nepal (+977)", value: "Nepal (+977)" },
  { label: "Malaysia (+60)", value: "Malaysia (+60)" },
  { label: "Singapore (+65)", value: "Singapore (+65)" },
  { label: "Thailand (+66)", value: "Thailand (+66)" },
  { label: "Indonesia (+62)", value: "Indonesia (+62)" },
  { label: "China (+86)", value: "China (+86)" },
  { label: "Japan (+81)", value: "Japan (+81)" },
  { label: "South Korea (+82)", value: "South Korea (+82)" },
  { label: "Turkey (+90)", value: "Turkey (+90)" },
  { label: "Egypt (+20)", value: "Egypt (+20)" },
  { label: "South Africa (+27)", value: "South Africa (+27)" },
  { label: "Nigeria (+234)", value: "Nigeria (+234)" },
  { label: "Kenya (+254)", value: "Kenya (+254)" },
  { label: "Brazil (+55)", value: "Brazil (+55)" },
  { label: "Mexico (+52)", value: "Mexico (+52)" },
  { label: "Argentina (+54)", value: "Argentina (+54)" },
];
